### ISSUE TITLE
Decide polars namespace extension implementations

### ISSUE THREAD

**Issue by TomBurdge** [TomBurdge/harley#2]
polars allows [namespace extensions](https://docs.pola.rs/api/python/stable/reference/api.html) for plugins to extend the API.

I think for *some* of the functions it makes sense to extend the API, and for others it doesn't.
These probably won't be any cause for debate/discussion, I imagine there can be just quick agreeement for each new feature.

* expr namespace for the col transforms.
* DataFrame & LazyFrame namespace for the Frame transforms.
* Series - do any need this?

And then, _ for the base functions which shouldn't be used outside of the namespace extension.?

Some functions, such as schema_from_csv will be no namespace extension and can be a raw function with no preceding `_`.

**Comment by LyndonFan** [comment]
Agree with the naming conventions -- seems like we should only expose them under the namespaces.
For Series, maybe we can add transformations which also return a single column? e.g. include `anti_trim`, but exclude `flatten_struct`

**Comment by TomBurdge** [comment]
I have changed my perspective a bit on the name spaces. 

At PyData London Marco Gorelli gave a talk where he said that he felt the .`plugin`.`method` namespace extensions were worse syntax than a plain function. He requested that if you expose the methods to the polars namespace with `register` then plse also expose it as a pure function without an `_` so that the user can choose. I think I actually overall I agree with Marco, but acn also extend the API too. But I think, we can do both based on this, what do you think? @LyndonFan 

Say `anti_trim` should probably be a column expression, and therefore should be part of the expressions api which can work across DataFrame/Series.

**Comment by LyndonFan** [comment]
Agreed, let's expose it both ways
