### ISSUE TITLE
Snake case column names feature

### ISSUE THREAD

**Issue by TomBurdge** [TomBurdge/harley#7]
Original discussion came from this, it looks like we might be able to cover this with:
https://github.com/kevinheavey/pyheck

this is actually python bindings for a rust crate (I saw this when looking at py03 docs).
https://github.com/kevinheavey/pyheck

Could:
* Add the lib as a dependency
* Add the crate as a depedency and implement a call from py03 (probably preferable? We could iterate over each column a bit quicker like this, and we are already using py03 functions)
* just copy some of the snake case rust code and if we don't want to add any dependency/want to change something.

**Comment by TomBurdge** [comment]
@LyndonFan do you think the tests at the bottom look complete enough?
They look decent to me
https://github.com/withoutboats/heck/blob/master/src/snake.rs
I think we would need to add test for stripping preceding/following blank space.

**Comment by LyndonFan** [comment]
As much as re-implementing the snake case functionality is a good challenge, I think it might be overkill.
Let's try importing it on the rust side which doesn't sound hard.
Also I installed pyheck and checked it does strip whitespace characters with its `snake` function, so its Rust counterpart should as well

**Comment by TomBurdge** [comment]
cool, nice yeah agreed there's no point over-engineering it.
Using the heck crate should be pretty straightforward with Py03.
